language: node_js
node_js:
- '5.7'
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: eWjIDngtyMHIFIpThaAoYf6HEdoUR1jpRXCl6Jm1taDAzWzEmsIA3pCT3Wjb+ZbqGobMG08KGagsriwEoEF/N9ww/yZP5EDj/qnrTQMXQRc8+iMa6nrojpqrtcK/jSZWSEwxy89zuOxxkw+rfPUbGh4NoLHp9Xf8jev0Jf26U7q54x6RC2s63FryAhNTBiId8RQVmRWeoRap2ry7NKqcFyJ8fUt2UjZGaGVyJacqEO1pPUJbAeaqsMeGgL7HPLtzgMQLKh75kd5DEaoRh+ncUAtBHZM26Xpd8aABO9bEz/HC+f/jRq7vQJCuGMN0ttVDJ0CgyNC5dJRv42hNCE2E9Avia92YZOQgon0e8qUWKos25w4T/FXUhT3XJXyZjaXiN8/wTp+cD/MbNdrvIuSu7eBchOZzDzKWe3HTucJ1Ta7iSdBFSKGF7FyikQoK6uWbutZZhiog7p8BF4I/EM+eQ/gLH9zZ7G7KlyNb9zDZJYROtW/VSywvgYTWzUq9RdN3iAAITuBvTGhZe56R9BtUMiJQRnPwXv5s3TtLK0H/iOo39fih1A6R/pb2YVetyQ2S/jgYqkKZ6On+BbzydZCi8XVZ1Xrp3cQhM4Ay+G6a/+/ukq+F/XWVpg2D8FDWvY7tYm7UVqzpRQOxFyL9AM1sq8bhG5CsmYJBPyCOym/EytI=
