language: node_js
node_js:
- '5.7'
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: YkorVBwJywe99RYw64nHCBFNXPY7LM9/UsT4kV+Vt9u2dtvtJiXZyMPYciL2TaULXva/ECTr7aHT/p0y3PR1XO0Pa4UrzVjLc3CSJmPhtEGJ2DOp+xpKRaKyR6NZSBrEjyfYB0iE45P4IA9RhWtG2fl3ORJoAkWD58S26dqNAcBAZaCTpYfJmXRS6Iq4Y3RSzlviVwUUC/P+fZy5vWqqrIX87L2RlGLgpuWiZnk5Idi70q+hlmao1O7pFzn39z/WeMkZW8gjbIzviPMuQdA9eQrf3tnVNSN26z3DeoA3JuuYU81iUWrofuD497ZcIfibGn9oFhIgcVltkq3flbJG/YC0Ek3sma97sBMPAGHcG4wdljYDdgfkjWGfZJSwZn/3A/BXlZLrvXNGWQ87SG+MteUK/aw/mTlXiTQqv+XH/B8XIF5eoYL0UKIvlZlgLPWVgeuDBDgQZc3WLOGoJJsoVhOtY+whMf1Mh+7VaNXF8swYjOxR4v1hzwUAyztTQmLwnUWYa7AFiyMY9LyOJml679Uee2xLL9TqC7e0NaVFsrFNBmUlpKR1YxOmd4xWOWEqLkGytClVUacV/tWf4/qreVzllHLIV08vlz5VAlb0SpD8exiMQ5vi83wXmuqEOi6WXA9xXgM77eAZfZKrLxI2eWfIp9YzBinTybRWwyZFDpM=
